In [1]:
import numpy as np

In [7]:
X_train_arr = np.load('../temp/X_train_arr.npy')
Y_train_arr = np.load('../temp/y_train_arr.npy')

In [4]:
print(len(X_train_arr))

61440


In [5]:
print(Y_train_arr.shape)

(61440, 3)


In [6]:
print(X_train_arr)

[[0.16691309 0.25104993 0.42591919 ... 1.09575709 0.8408682  0.53955971]
 [0.10424499 0.97618429 0.70921373 ... 0.92584121 0.83716906 0.6382961 ]
 [0.11708856 0.28935476 0.49228768 ... 1.13441662 0.82112418 1.02343517]
 ...
 [0.18400853 0.27098127 0.47903724 ... 1.30816531 1.06745518 0.89807444]
 [0.14869185 1.61671335 1.33261707 ... 1.34324877 1.08356474 0.72464693]
 [0.06244188 0.30635844 0.41498375 ... 0.93883551 1.05751923 0.80876793]]


In [8]:
label_counts = np.sum(Y_train_arr, axis=0)
print("Label counts:", label_counts)

Label counts: [20480. 20480. 20480.]
